### ISSUE TITLE
Plugins description overlaps with other buttons

### ISSUE THREAD

**Issue by Loup-Garou911XD** [bombsquad-community/plugin-manager#111]
I suggest we increase the window size since there isn't much space

**Comment by deepgohil** [comment]
I would like to solve this issue.

**Comment by rikkolovescats** [comment]
@deepgohil sure, feel free to ask away any questions you may have!

**Comment by kingsamurai123** [comment]
The above change in laptop everything seems to be fine. But in my mobile, last two letters of the plugin descriptions (bomb radius, pro unlocker, pratice tools) still overlapping with the source button.

**Comment by Loup-Garou911XD** [comment]
Closes by #113
