### ISSUE TITLE
DEPRACTION IN 3.11

### ISSUE THREAD

**Issue by brostosjoined** [bombsquad-community/plugin-manager#129]
https://github.com/bombsquad-community/plugin-manager/blob/97a4a6a244e3bf78366c5f14600c1f2ac4dd8340/plugin_manager.py#L68

Some little headsup @rikkolovescats  https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop

**Comment by rikkolovescats** [comment]
thanks! i don't think any changes should be required in plugin manager since event loop should already be set at all times from here, unless i'm missing something:
https://github.com/bombsquad-community/plugin-manager/blob/97a4a6a244e3bf78366c5f14600c1f2ac4dd8340/plugin_manager.py#L2322

**Comment by brostosjoined** [comment]
Seems perfect good. Closing the issue as complete.

**Comment by rikkolovescats** [comment]
closed by https://github.com/bombsquad-community/plugin-manager/pull/193
