### ISSUE TITLE
Show all authors and their social handles for a plugin

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#134]
...and their discord handle, email address, etc. if any.

--------------------

we currently show only the first author for a plugin in-game:

<img src="https://github.com/bombsquad-community/plugin-manager/assets/106954762/5533ca9f-15cf-4324-b6c6-cfda527d6eee" width="600">

even when this plugin's got multiple authors:
https://github.com/bombsquad-community/plugin-manager/blob/4948d8b3af8457412eaa25b0d860a428a37c1a91/plugins/minigames.json#L315-L329

--------------------

i've been thinking about having tiny button "..." next to the first author's name, which when tapped on will open a new window displaying all author names and their social handles.

**Comment by Loup-Garou911XD** [comment]
I'll try it day after tomorrow

**Comment by rikkolovescats** [comment]
sure, whenever you feel like, take your time! maybe we could even invite new contributors to help with this.
