### ISSUE TITLE
[Question] Related to 1.8

### ISSUE THREAD

**Issue by Freaku17** [bombsquad-community/plugin-manager#146]
Hi, I just recently noticed that Bombsquad is slowing starting to move to API 8. So I have the following 2 questions:

1. What is the estimated time of release of 1.8 to the global platform? (especially Google Play Store)
2. Who & how will the mods be updated to 1.8?
Since there are modders who may not be available to update their mods, so someone else has to take up their work

**Comment by Loup-Garou911XD** [comment]
Hello there
Bombsquad is currently in 1.7.20 alpha,it will be in beta stages in 3-4 days probably,after that the work on 1.8 should begin
1.7.20 will introduce api 8 which mostly is moving stuff around,so it should be easy to update the plugins with a simple script that changes the old packages and module names with new ones,like how it was from api 6 to api 7

**Comment by rikkolovescats** [comment]
^this script is now moved to https://github.com/bombsquad-community/baport
