### ISSUE TITLE
deprecated method

### ISSUE THREAD

**Issue by Loup-Garou911XD** [bombsquad-community/plugin-manager#201]
https://github.com/bombsquad-community/plugin-manager/blob/54b35309f49ed7e3f567019129f79541b589e2a9/plugins/utilities/file_share.py#L34C7-L34C7

use `app = _babase.app.env` instead

**Comment by Loup-Garou911XD** [comment]
babase also has `babase.app.env.python_directory_user` attribute so why using _babase

**Comment by rikkolovescats** [comment]
fixed in https://github.com/bombsquad-community/plugin-manager/pull/202

> babase also has `babase.app.env.python_directory_user` attribute so why using _babase?

shouldn't make a difference either way
