### ISSUE TITLE
This content is no longer available.

### ISSUE THREAD

**Issue by Konyolodon** [bombsquad-community/plugin-manager#243]
This content is no longer available.

**Comment by rikkolovescats** [comment]
i'm assuming it have something to do with github api having issues when you were trying out plugin manager.

closing this, feel free to re-open and add in more details if this issue's still happening.

**Comment by rikkolovescats** [comment]
i'm assuming it had something to do with github api having issues when you were trying out plugin manager.

closing this, feel free to re-open and add in more details if this issue's still happening.
