### ISSUE TITLE
Display a message with the latest changelog in-game when plugin manager gets updated

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#247]
it is unlikely that we'll miss a changelog entry whenever a new plugin manager version is released, as we have a unit test that checks for a changelog entry in CHANGELOG.md corresponding to every plugin manager version.

it seems a nice idea to display a screenmessage in-game with the contents of latest changelog entry whenever plugin manager gets updated.

#246 might help with this.

**Comment by Loup-Garou911XD** [comment]
We can use this script for getting change logs
https://github.com/bombsquad-community/plugin-manager/blob/main/test%2Fget_changes.py

**Comment by Loup-Garou911XD** [comment]
#268 added a window for viewing  changelog which is a better solution than a screenmessage imo
