### ISSUE TITLE
How to update the plugin manager for API 9?

### ISSUE THREAD

**Issue by sojoyork** [bombsquad-community/plugin-manager#311]
Just wanna use plugin manager... AND THAT IS THE PROBLEM :(
How do i update it to API 9?

**Comment by Loup-Garou911XD** [comment]
> Just wanna use plugin manager... AND THAT IS THE PROBLEM :(
> How do i update it to API 9?

Api 9 is still in beta phase I would say
So we don't have a api 9 release yet

**Comment by Loup-Garou911XD** [comment]
It will be updated to api 9 as soon as bombsquad 1.7.37 releases
