### ISSUE TITLE
Minigames not showing up

### ISSUE THREAD

**Issue by Loup-Garou911XD** [bombsquad-community/plugin-manager#33]
Minigames like alliance_elimination, volleyball and musical_flags not showing up in menu.How do i start the minigame?

**Comment by rikkolovescats** [comment]
Hi! Those will be visible when you create/edit a playlist. Check out this video at 2:20.
https://www.youtube.com/watch?v=gUaWdjcmY-w&t=140s

**Comment by Loup-Garou911XD** [comment]
So i need bomb squad pro for doing that,are there any other ways?I understand if there isn't.

**Comment by rikkolovescats** [comment]
I see. There's also a pro unlocker kinda plugin (currently not in this repo) which lifts a few restrictions. I'll check it out if it'll help in your case and let you know.

**Comment by Loup-Garou911XD** [comment]
Would be very generous or you 😊!

**Comment by rikkolovescats** [comment]
It's been added in #34. You should see a new plugin named as `pro_unlocker` in your plugin manager.

**Comment by Loup-Garou911XD** [comment]
I appreciate the efforts but might i ask you to reconsider adding it to the plugin manager because it might hurt developer's income and knowing that he is a solo man team who lives on income from bombsquad,i won't complain for whatever decision you take because i myself wouldn't leave the opportunity to use such a plugin but maybe just reconsider adding it.Thanks!

**Comment by rikkolovescats** [comment]
Yep, I'll update the plugin's description to include supporting the game developer, and also well, this stuff kinda stuff could stop working any time if the game developer implemented pro accounts checks on the server side.

**Comment by Loup-Garou911XD** [comment]
Ok thanks
