### ISSUE TITLE
Specify which versions to auto-update plugin manager to

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#49]
Let's have a new bool field (`can_auto_update_to`?) in plugin manager version metadata:
https://github.com/bombsquad-community/plugin-manager/blob/b8d70aea65255c7b5e9c99c3838d7ac474598245/index.json#L4-L9
If this field is `false` then previous plugin manager versions should not auto-update to this new version. This will help in releasing experimental changes.

**Comment by vishal332008** [comment]
@rikkolovescats , if it is experimental, just not adding `'1.x.x': null,` in index.json is enough to stop release. After we finished testing experimental changes, we can release it by adding the version to index.json.
