### ISSUE TITLE
Show plugin's external url in plugin manager ui

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#52]
We store a plugin's external url in case there is one, in category json metadata file:

https://github.com/bombsquad-community/plugin-manager/blob/c05e7060c3ab36a03188c2ca7d128d9956faeefc/plugins/utilities.json#L212-L214

but this currently isn't being used anywhere in the plugin manager in-game.

**Comment by kingsamurai123** [comment]
Hi Rikko,
Made the changes as I thought was right. Let me know if there is anything wrong in this.
Texture used is "frameInset" as the "file" texture is blocking the letters (less visibility). Let me know if this is wrong.

**Comment by Loup-Garou911XD** [comment]
Closed by #109
