### ISSUE TITLE
Replace `on_plugin_manager_prompt` method with the official methods

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#60]
[v1.7.11](https://github.com/efroemling/ballistica/blob/master/CHANGELOG.md#1711-build-20909-api-7-2022-10-15) officially features `has_settings_ui` and `show_settings_ui` methods. That means we can remove the current `on_plugin_manager_prompt` method in plugin manager and instead make use of these new ones!

**Comment by Loup-Garou911XD** [comment]
The show_settings_ui method is called with the settings button widget as an argument,not sure how to implement it in plugin manager.One idea is we could pass a dummy button widget so that code works without needing to handle exceptions or creating if statement

**Comment by Loup-Garou911XD** [comment]
If that's how we want to do it then I can create a pr
