### ISSUE TITLE
Show author names, new plugins in the main plugin manager window(?)

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#74]
![image](https://user-images.githubusercontent.com/106954762/204122668-1a38a719-b7b7-4b20-badc-2f83dba47e72.png)

There's a lot of empty stuff to the right of plugin names which can be used to display useful info. This will require us to create our own custom ui handler for widgets which can be a little complexy. Check out Gather -> Public -> Join a Public Party window for an example.

**Comment by kingsamurai123** [comment]
![image](https://user-images.githubusercontent.com/42110198/209084096-14183ea6-c0ca-4c29-89df-f9c1da3715d5.jpeg)
Since this requires only one change. Made it like this. Another reason is as shown in the image, there are names which are tool long to display in a separate text box like in public server details. So is this fine or need to the exact replica of public server page?

**Comment by Loup-Garou911XD** [comment]
Having a seperate text widget so we can format it differently would be how we should do it but idk,Rikko makes the call

**Comment by TheMikirog** [comment]
Personally I like how it is currently with just the mod name. What the mod is is much more important than the author, at least from the user's perspective. This change just makes the mod menu much more cluttered and less readable.

I think this change is ultimately pointless and more info is already shown when you select the mod. As it should be.

**Comment by kingsamurai123** [comment]
Thanks loup and miki for your inputs. If this is not required. Then it is better to close this, right?

**Comment by rikkolovescats** [comment]
I thought about this and it doesn't seem like there's any other information important enough to users. We'll only be stretching the plugin manager window to fit in this extra fields. See #103.
