### ISSUE TITLE
Why is this under that if statement 

### ISSUE THREAD

**Issue by Loup-Garou911XD** [bombsquad-community/plugin-manager#83]
https://github.com/bombsquad-community/plugin-manager/blob/ca8a3006a3343f8af258cb601b505f78dd2f7a62/plugins/utilities/server_switch.py#L17

**Comment by Loup-Garou911XD** [comment]
I also saw Eric did it somewhere 😜

**Comment by rikkolovescats** [comment]
most likely when python has type checking support enabled (`TYPE_CHECKING ==  True`), stuff like this could raise an exception like `ba` not defined, such as here:
https://github.com/efroemling/ballistica/blob/1e8ad4361dd1b367c2777357115234cf49057b49/assets/src/ba_data/python/ba/_campaign.py#L35
