### ISSUE TITLE
easy_connect plugin sometimes overlaps filtered results

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#94]
using easy_connect v1.2.1 on test desktop build of the game on v1.7.13:

![image](https://user-images.githubusercontent.com/106954762/208455941-078af2ea-a0bf-419d-b10d-b97ea0f00701.png)

**Comment by imayushsaini** [comment]
Fixed in eb205fe7b18deef7277eea895e7ec13c74e44ddb
